"""empty message

Revision ID: 05765c8c848a
Revises: fab6d8c70333
Create Date: 2022-10-26 11:26:44.033115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05765c8c848a'
down_revision = 'fab6d8c70333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('seller_id', sa.String(length=120), nullable=True))
    op.add_column('order', sa.Column('seller_username', sa.String(length=120), nullable=True))
    op.drop_column('order', 'seller')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('seller', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('order', 'seller_username')
    op.drop_column('order', 'seller_id')
    # ### end Alembic commands ###
