"""empty message

Revision ID: 0852d1715e63
Revises: 99fc5cf7dbc4
Create Date: 2022-10-05 19:39:56.481126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0852d1715e63'
down_revision = '99fc5cf7dbc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('user', 'phone',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
