"""empty message

Revision ID: 093373f863e9
Revises: 862156f5c3df
Create Date: 2022-10-08 18:35:18.752837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093373f863e9'
down_revision = '862156f5c3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.NUMERIC(precision=120, scale=0),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=120, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###
