"""empty message

Revision ID: 09d125ff6fbc
Revises: 89979870f97e
Create Date: 2022-10-06 16:49:24.815105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d125ff6fbc'
down_revision = '89979870f97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('by_product', sa.Column('location', sa.Numeric(precision=120), nullable=True))
    op.drop_column('by_product', 'locationX')
    op.drop_column('by_product', 'locationY')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('by_product', sa.Column('locationY', sa.NUMERIC(precision=120, scale=0), autoincrement=False, nullable=True))
    op.add_column('by_product', sa.Column('locationX', sa.NUMERIC(precision=120, scale=0), autoincrement=False, nullable=True))
    op.drop_column('by_product', 'location')
    # ### end Alembic commands ###
