"""empty message

Revision ID: 0ae21c2a8c94
Revises: 39700e34a8ec
Create Date: 2022-10-21 07:46:09.563820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae21c2a8c94'
down_revision = '39700e34a8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'img',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'img',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
