"""empty message

Revision ID: 133e736f154e
Revises: 1101cd34e8e9
Create Date: 2022-10-13 14:22:35.100688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133e736f154e'
down_revision = '1101cd34e8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basket', 'total')
    op.drop_column('basket_row', 'quantity')
    op.drop_column('basket_row', 'subtotal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket_row', sa.Column('subtotal', sa.NUMERIC(precision=120, scale=0), autoincrement=False, nullable=True))
    op.add_column('basket_row', sa.Column('quantity', sa.NUMERIC(precision=120, scale=0), autoincrement=False, nullable=True))
    op.add_column('basket', sa.Column('total', sa.NUMERIC(precision=120, scale=0), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
