"""empty message

Revision ID: 2ba443a4036d
Revises: 9b27139a62f0
Create Date: 2022-11-15 10:50:48.431661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba443a4036d'
down_revision = '9b27139a62f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('buyer_id', sa.Integer(), nullable=True))
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['buyer_id'], ['id'])
    op.drop_column('order', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'])
    op.drop_column('order', 'buyer_id')
    # ### end Alembic commands ###
