"""empty message

Revision ID: 34eeae74d3d7
Revises: ea3256faed3d
Create Date: 2022-10-18 14:56:35.330676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34eeae74d3d7'
down_revision = 'ea3256faed3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('seller', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'seller')
    # ### end Alembic commands ###
