"""empty message

Revision ID: 63225c48a190
Revises: 0ae21c2a8c94
Create Date: 2022-10-21 08:17:11.984805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63225c48a190'
down_revision = '0ae21c2a8c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('path', sa.Text(), nullable=False))
    op.drop_constraint('image_img_key', 'image', type_='unique')
    op.create_unique_constraint(None, 'image', ['path'])
    op.drop_column('image', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('img', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'image', type_='unique')
    op.create_unique_constraint('image_img_key', 'image', ['img'])
    op.drop_column('image', 'path')
    # ### end Alembic commands ###
