"""empty message

Revision ID: 68282475df2b
Revises: 78a433801430
Create Date: 2022-10-17 08:43:06.166144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68282475df2b'
down_revision = '78a433801430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('basket_item', 'quantity',
               existing_type=sa.NUMERIC(precision=120, scale=0),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('basket_item', 'subtotal',
               existing_type=sa.NUMERIC(precision=120, scale=0),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('order_row', 'quantity',
               existing_type=sa.NUMERIC(precision=120, scale=0),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('order_row', 'subtotal',
               existing_type=sa.NUMERIC(precision=120, scale=0),
               type_=sa.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_row', 'subtotal',
               existing_type=sa.FLOAT(),
               type_=sa.NUMERIC(precision=120, scale=0),
               existing_nullable=True)
    op.alter_column('order_row', 'quantity',
               existing_type=sa.FLOAT(),
               type_=sa.NUMERIC(precision=120, scale=0),
               existing_nullable=True)
    op.alter_column('basket_item', 'subtotal',
               existing_type=sa.FLOAT(),
               type_=sa.NUMERIC(precision=120, scale=0),
               existing_nullable=True)
    op.alter_column('basket_item', 'quantity',
               existing_type=sa.FLOAT(),
               type_=sa.NUMERIC(precision=120, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###
