"""empty message

Revision ID: 78a433801430
Revises: 62a3dee209de
Create Date: 2022-10-17 08:31:53.232281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a433801430'
down_revision = '62a3dee209de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket_item', sa.Column('quantity', sa.Numeric(precision=120), nullable=True))
    op.add_column('basket_item', sa.Column('subtotal', sa.Numeric(precision=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basket_item', 'subtotal')
    op.drop_column('basket_item', 'quantity')
    # ### end Alembic commands ###
