"""empty message

Revision ID: 861fe01efe7a
Revises: 2ba443a4036d
Create Date: 2022-11-15 11:02:13.594226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861fe01efe7a'
down_revision = '2ba443a4036d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('buyer_username', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'buyer_username')
    # ### end Alembic commands ###
