"""empty message

Revision ID: 89979870f97e
Revises: 0852d1715e63
Create Date: 2022-10-06 15:25:22.636376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89979870f97e'
down_revision = '0852d1715e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_phone_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_phone_key', 'user', ['phone'])
    # ### end Alembic commands ###
