"""empty message

Revision ID: cbb1dac13678
Revises: 34eeae74d3d7
Create Date: 2022-10-19 08:29:56.676819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb1dac13678'
down_revision = '34eeae74d3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'total',
               existing_type=sa.NUMERIC(precision=120, scale=0),
               type_=sa.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'total',
               existing_type=sa.FLOAT(),
               type_=sa.NUMERIC(precision=120, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###
