"""empty message

Revision ID: def41cec24d3
Revises: 09d125ff6fbc
Create Date: 2022-10-06 16:57:36.203983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def41cec24d3'
down_revision = '09d125ff6fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('byproduct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('stock', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Numeric(precision=120), nullable=True),
    sa.Column('location', sa.Numeric(precision=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('by_product')
    op.add_column('basket_row', sa.Column('byproduct_id', sa.Integer(), nullable=True))
    op.drop_constraint('basket_row_by_product_id_fkey', 'basket_row', type_='foreignkey')
    op.create_foreign_key(None, 'basket_row', 'byproduct', ['byproduct_id'], ['id'])
    op.drop_column('basket_row', 'by_product_id')
    op.add_column('image', sa.Column('byproduct_id', sa.Integer(), nullable=True))
    op.drop_constraint('image_by_product_id_fkey', 'image', type_='foreignkey')
    op.create_foreign_key(None, 'image', 'byproduct', ['byproduct_id'], ['id'])
    op.drop_column('image', 'by_product_id')
    op.add_column('order_row', sa.Column('byproduct_id', sa.Integer(), nullable=True))
    op.drop_constraint('order_row_by_product_id_fkey', 'order_row', type_='foreignkey')
    op.create_foreign_key(None, 'order_row', 'byproduct', ['byproduct_id'], ['id'])
    op.drop_column('order_row', 'by_product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_row', sa.Column('by_product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_row', type_='foreignkey')
    op.create_foreign_key('order_row_by_product_id_fkey', 'order_row', 'by_product', ['by_product_id'], ['id'])
    op.drop_column('order_row', 'byproduct_id')
    op.add_column('image', sa.Column('by_product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.create_foreign_key('image_by_product_id_fkey', 'image', 'by_product', ['by_product_id'], ['id'])
    op.drop_column('image', 'byproduct_id')
    op.add_column('basket_row', sa.Column('by_product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'basket_row', type_='foreignkey')
    op.create_foreign_key('basket_row_by_product_id_fkey', 'basket_row', 'by_product', ['by_product_id'], ['id'])
    op.drop_column('basket_row', 'byproduct_id')
    op.create_table('by_product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('stock', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=120, scale=0), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('location', sa.NUMERIC(precision=120, scale=0), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], name='by_product_type_id_fkey'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name='by_product_unit_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='by_product_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='by_product_pkey')
    )
    op.drop_table('byproduct')
    # ### end Alembic commands ###
