"""empty message

Revision ID: fab6d8c70333
Revises: 63225c48a190
Create Date: 2022-10-26 11:01:28.891812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab6d8c70333'
down_revision = '63225c48a190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_row', sa.Column('prod_name', sa.String(length=120), nullable=True))
    op.add_column('order_row', sa.Column('price', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_row', 'price')
    op.drop_column('order_row', 'prod_name')
    # ### end Alembic commands ###
